version: "3.5"
services:
  postgres:
    image: arm32v7/postgres:10
    volumes:
      - "/mnt/data/postgres:/var/lib/postgresql/data/pgdata"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    deploy:
      placement:
        constraints:
          - node.labels.role == data
    networks:
      - bobnet-data
    secrets:
      - pg_password

networks:
  bobnet-data:
    external: true

secrets:
  pg_password:
    external: true
