version: "3.5"
services:
  rabbitmq:
    image: robyoung/rabbitmq:002
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/rabbit_password
    ports:
      - "1883:1883"    # MQTT non-TLS
      - "15672:15672"  # UI non-TLS
      - "5672:5672"    # AMQP non-TLS

      # - "8883:8883"    # MQTT TLS
      # - "15671:15671"  # UI TLS
      # - "5671:5671"    # AMQP TLS
    networks:
      - bobnet-messaging
    secrets:
      - rabbit_password
    deploy:
      placement:
        constraints:
          - node.labels.role == dmz
  setup:
    image: robyoung/rabbitmq-setup:001
    networks:
      - bobnet-messaging
    secrets:
      - rabbit_password
      - devices_password
    deploy:
      placement:
        constraints:
          - node.labels.role == dmz
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  bobnet-messaging:
    external: true

secrets:
  rabbit_password:
    external: true

  devices_password:
    external: true
